import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SampleLibProvider } from "sample-react-library";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SampleLibProvider
          options={{ btnId: "next-btn", headingId: "next-heading" }}
        >
          {children}
        </SampleLibProvider>
      </body>
    </html>
  );
}
